version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./node_modules:/var/www/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - .env.docker

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tekrem_dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

  npm:
    image: node:20
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./node_modules:/var/www/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  mysql_data:
