import React, { useEffect, useRef } from 'react';
import { usePage } from '@inertiajs/react';

export default function MakoAd() {
  const { props } = usePage();
  const mako = (props as any).mako;
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!mako || !mako.apiUrl || !mako.campaignId) {
      console.warn('Mako integration details are missing in page props.');
      return;
    }

    const container = containerRef.current;
    if (!container) return;

    // Clear any previous elements inside the container wrapper
    container.innerHTML = '';

    // Create the script tag dynamically
    const script = document.createElement('script');
    const cleanApiUrl = mako.apiUrl.replace(/\/$/, ''); // Remove trailing slash if present
    script.src = `${cleanApiUrl}/embed-ads/widget/${mako.campaignId}.js`;
    script.async = true;
    script.setAttribute('data-mako-ad', 'true');

    // Append script to container
    container.appendChild(script);

    return () => {
      // Cleanup script and elements generated by the widget
      if (container) {
        container.innerHTML = '';
      }
    };
  }, [mako]);

  if (!mako || !mako.campaignId) {
    return null;
  }

  return (
    <div 
      className="w-full max-w-[728px] mx-auto my-12 px-4 transition-all duration-300 ease-in-out hover:scale-[1.01]"
      style={{ minHeight: '100px' }}
    >
      <div className="text-[10px] uppercase tracking-wider text-gray-400 dark:text-gray-500 mb-2 font-semibold text-center">
        Sponsored Ad
      </div>
      <div ref={containerRef} id="mako-ad-container" className="relative rounded-2xl overflow-hidden shadow-sm dark:shadow-none border border-gray-100 dark:border-gray-800" />
    </div>
  );
}
